package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService;
//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/15/2017 9:13:05 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService.Centro;
import package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService.Provincia;
import package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService.SolicitudServicio;
import package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService.TipoMatricula;
import package com.example.cramirez.appreportingwcf.Wsdl2Code.WebServices.MostradorService.VectorByte;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class SolicitudVehiculoSaliente implements KvmSerializable {
    
    public String bastidor;
    public int cMA;
    public boolean cMASpecified;
    public boolean cambioManual;
    public boolean cambioManualSpecified;
    public Centro centro;
    public int cilindada;
    public boolean cilindadaSpecified;
    public boolean conRemolque;
    public boolean conRemolqueSpecified;
    public boolean conTurbo;
    public boolean conTurboSpecified;
    public String contrasenyaHomologacion;
    public boolean cuatroTiempos;
    public boolean cuatroTiemposSpecified;
    public String estacionUltimaValidez;
    public String extensionBastidor;
    public long fK_IdCombustible;
    public boolean fK_IdCombustibleSpecified;
    public long fK_IdEstacionUltimaValidez;
    public boolean fK_IdEstacionUltimaValidezSpecified;
    public long fK_IdMarcaVehiculo;
    public boolean fK_IdMarcaVehiculoSpecified;
    public long fK_IdModeloVehiculo;
    public boolean fK_IdModeloVehiculoSpecified;
    public long fK_IdProvinciaPrimeraMatriculacion;
    public boolean fK_IdProvinciaPrimeraMatriculacionSpecified;
    public long fK_IdSolicitud;
    public boolean fK_IdSolicitudSpecified;
    public long fK_IdTipoMatricula;
    public boolean fK_IdTipoMatriculaSpecified;
    public long fK_IdVehiculoClasificacion;
    public boolean fK_IdVehiculoClasificacionSpecified;
    public String fechaPrimeraMatriculacion;
    public boolean fechaPrimeraMatriculacionSpecified;
    public String fechaUltimaValidez;
    public boolean fechaUltimaValidezSpecified;
    public long idSolicitudVehiculoSaliente;
    public boolean idSolicitudVehiculoSalienteSpecified;
    public String lugarPrimeraMatriculacion;
    public int mOM;
    public boolean mOMSpecified;
    public String matricula;
    public String notasOcultas;
    public int numEjes;
    public boolean numEjesSpecified;
    public String observaciones;
    public int pMA;
    public boolean pMASpecified;
    public int plazas;
    public boolean plazasSpecified;
    public int potenciaFiscal;
    public boolean potenciaFiscalSpecified;
    public Provincia provincia;
    public boolean publicado;
    public boolean publicadoSpecified;
    public SolicitudServicio solicitudServicio;
    public String tipoFichaTecnica;
    public String tipoMarcaModelo;
    public TipoMatricula tipoMatricula;
    public int velocidadMaxima;
    public boolean velocidadMaximaSpecified;
    public String fechaModificacion;
    public boolean fechaModificacionSpecified;
    public VectorByte timestamp;
    public long usuarioModificacion;
    public boolean usuarioModificacionSpecified;
    public String id;
    public String ref;
    
    public SolicitudVehiculoSaliente(){}
    
    public SolicitudVehiculoSaliente(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Bastidor"))
        {
            Object obj = soapObject.getProperty("Bastidor");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                bastidor = j.toString();
            }else if (obj!= null && obj instanceof String){
                bastidor = (String) obj;
            }
        }
        if (soapObject.hasProperty("CMA"))
        {
            Object obj = soapObject.getProperty("CMA");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cMA = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                cMA = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("CMASpecified"))
        {
            Object obj = soapObject.getProperty("CMASpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cMASpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cMASpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("CambioManual"))
        {
            Object obj = soapObject.getProperty("CambioManual");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cambioManual = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cambioManual = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("CambioManualSpecified"))
        {
            Object obj = soapObject.getProperty("CambioManualSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cambioManualSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cambioManualSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Centro"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Centro");
            centro =  new Centro (j);
            
        }
        if (soapObject.hasProperty("Cilindada"))
        {
            Object obj = soapObject.getProperty("Cilindada");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cilindada = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                cilindada = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("CilindadaSpecified"))
        {
            Object obj = soapObject.getProperty("CilindadaSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cilindadaSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cilindadaSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("ConRemolque"))
        {
            Object obj = soapObject.getProperty("ConRemolque");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                conRemolque = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                conRemolque = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("ConRemolqueSpecified"))
        {
            Object obj = soapObject.getProperty("ConRemolqueSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                conRemolqueSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                conRemolqueSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("ConTurbo"))
        {
            Object obj = soapObject.getProperty("ConTurbo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                conTurbo = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                conTurbo = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("ConTurboSpecified"))
        {
            Object obj = soapObject.getProperty("ConTurboSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                conTurboSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                conTurboSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("ContrasenyaHomologacion"))
        {
            Object obj = soapObject.getProperty("ContrasenyaHomologacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                contrasenyaHomologacion = j.toString();
            }else if (obj!= null && obj instanceof String){
                contrasenyaHomologacion = (String) obj;
            }
        }
        if (soapObject.hasProperty("CuatroTiempos"))
        {
            Object obj = soapObject.getProperty("CuatroTiempos");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cuatroTiempos = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cuatroTiempos = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("CuatroTiemposSpecified"))
        {
            Object obj = soapObject.getProperty("CuatroTiemposSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cuatroTiemposSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                cuatroTiemposSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("EstacionUltimaValidez"))
        {
            Object obj = soapObject.getProperty("EstacionUltimaValidez");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                estacionUltimaValidez = j.toString();
            }else if (obj!= null && obj instanceof String){
                estacionUltimaValidez = (String) obj;
            }
        }
        if (soapObject.hasProperty("ExtensionBastidor"))
        {
            Object obj = soapObject.getProperty("ExtensionBastidor");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                extensionBastidor = j.toString();
            }else if (obj!= null && obj instanceof String){
                extensionBastidor = (String) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdCombustible"))
        {
            Object obj = soapObject.getProperty("FK_IdCombustible");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdCombustible = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdCombustible = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdCombustibleSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdCombustibleSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdCombustibleSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdCombustibleSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdEstacionUltimaValidez"))
        {
            Object obj = soapObject.getProperty("FK_IdEstacionUltimaValidez");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdEstacionUltimaValidez = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdEstacionUltimaValidez = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdEstacionUltimaValidezSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdEstacionUltimaValidezSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdEstacionUltimaValidezSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdEstacionUltimaValidezSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdMarcaVehiculo"))
        {
            Object obj = soapObject.getProperty("FK_IdMarcaVehiculo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdMarcaVehiculo = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdMarcaVehiculo = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdMarcaVehiculoSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdMarcaVehiculoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdMarcaVehiculoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdMarcaVehiculoSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdModeloVehiculo"))
        {
            Object obj = soapObject.getProperty("FK_IdModeloVehiculo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdModeloVehiculo = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdModeloVehiculo = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdModeloVehiculoSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdModeloVehiculoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdModeloVehiculoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdModeloVehiculoSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdProvinciaPrimeraMatriculacion"))
        {
            Object obj = soapObject.getProperty("FK_IdProvinciaPrimeraMatriculacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdProvinciaPrimeraMatriculacion = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdProvinciaPrimeraMatriculacion = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdProvinciaPrimeraMatriculacionSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdProvinciaPrimeraMatriculacionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdProvinciaPrimeraMatriculacionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdProvinciaPrimeraMatriculacionSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdSolicitud"))
        {
            Object obj = soapObject.getProperty("FK_IdSolicitud");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdSolicitud = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdSolicitud = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdSolicitudSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdSolicitudSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdSolicitudSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdSolicitudSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdTipoMatricula"))
        {
            Object obj = soapObject.getProperty("FK_IdTipoMatricula");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdTipoMatricula = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdTipoMatricula = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdTipoMatriculaSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdTipoMatriculaSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdTipoMatriculaSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdTipoMatriculaSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdVehiculoClasificacion"))
        {
            Object obj = soapObject.getProperty("FK_IdVehiculoClasificacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdVehiculoClasificacion = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                fK_IdVehiculoClasificacion = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("FK_IdVehiculoClasificacionSpecified"))
        {
            Object obj = soapObject.getProperty("FK_IdVehiculoClasificacionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fK_IdVehiculoClasificacionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fK_IdVehiculoClasificacionSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FechaPrimeraMatriculacion"))
        {
            Object obj = soapObject.getProperty("FechaPrimeraMatriculacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaPrimeraMatriculacion = j.toString();
            }else if (obj!= null && obj instanceof String){
                fechaPrimeraMatriculacion = (String) obj;
            }
        }
        if (soapObject.hasProperty("FechaPrimeraMatriculacionSpecified"))
        {
            Object obj = soapObject.getProperty("FechaPrimeraMatriculacionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaPrimeraMatriculacionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fechaPrimeraMatriculacionSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("FechaUltimaValidez"))
        {
            Object obj = soapObject.getProperty("FechaUltimaValidez");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaUltimaValidez = j.toString();
            }else if (obj!= null && obj instanceof String){
                fechaUltimaValidez = (String) obj;
            }
        }
        if (soapObject.hasProperty("FechaUltimaValidezSpecified"))
        {
            Object obj = soapObject.getProperty("FechaUltimaValidezSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaUltimaValidezSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fechaUltimaValidezSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("IdSolicitudVehiculoSaliente"))
        {
            Object obj = soapObject.getProperty("IdSolicitudVehiculoSaliente");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                idSolicitudVehiculoSaliente = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                idSolicitudVehiculoSaliente = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("IdSolicitudVehiculoSalienteSpecified"))
        {
            Object obj = soapObject.getProperty("IdSolicitudVehiculoSalienteSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                idSolicitudVehiculoSalienteSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                idSolicitudVehiculoSalienteSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("LugarPrimeraMatriculacion"))
        {
            Object obj = soapObject.getProperty("LugarPrimeraMatriculacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lugarPrimeraMatriculacion = j.toString();
            }else if (obj!= null && obj instanceof String){
                lugarPrimeraMatriculacion = (String) obj;
            }
        }
        if (soapObject.hasProperty("MOM"))
        {
            Object obj = soapObject.getProperty("MOM");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mOM = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                mOM = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("MOMSpecified"))
        {
            Object obj = soapObject.getProperty("MOMSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mOMSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                mOMSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Matricula"))
        {
            Object obj = soapObject.getProperty("Matricula");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                matricula = j.toString();
            }else if (obj!= null && obj instanceof String){
                matricula = (String) obj;
            }
        }
        if (soapObject.hasProperty("NotasOcultas"))
        {
            Object obj = soapObject.getProperty("NotasOcultas");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                notasOcultas = j.toString();
            }else if (obj!= null && obj instanceof String){
                notasOcultas = (String) obj;
            }
        }
        if (soapObject.hasProperty("NumEjes"))
        {
            Object obj = soapObject.getProperty("NumEjes");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numEjes = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                numEjes = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("NumEjesSpecified"))
        {
            Object obj = soapObject.getProperty("NumEjesSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numEjesSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                numEjesSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Observaciones"))
        {
            Object obj = soapObject.getProperty("Observaciones");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                observaciones = j.toString();
            }else if (obj!= null && obj instanceof String){
                observaciones = (String) obj;
            }
        }
        if (soapObject.hasProperty("PMA"))
        {
            Object obj = soapObject.getProperty("PMA");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pMA = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                pMA = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("PMASpecified"))
        {
            Object obj = soapObject.getProperty("PMASpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pMASpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                pMASpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Plazas"))
        {
            Object obj = soapObject.getProperty("Plazas");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                plazas = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                plazas = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("PlazasSpecified"))
        {
            Object obj = soapObject.getProperty("PlazasSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                plazasSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                plazasSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("PotenciaFiscal"))
        {
            Object obj = soapObject.getProperty("PotenciaFiscal");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                potenciaFiscal = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                potenciaFiscal = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("PotenciaFiscalSpecified"))
        {
            Object obj = soapObject.getProperty("PotenciaFiscalSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                potenciaFiscalSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                potenciaFiscalSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Provincia"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Provincia");
            provincia =  new Provincia (j);
            
        }
        if (soapObject.hasProperty("Publicado"))
        {
            Object obj = soapObject.getProperty("Publicado");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                publicado = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                publicado = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("PublicadoSpecified"))
        {
            Object obj = soapObject.getProperty("PublicadoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                publicadoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                publicadoSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("SolicitudServicio"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("SolicitudServicio");
            solicitudServicio =  new SolicitudServicio (j);
            
        }
        if (soapObject.hasProperty("TipoFichaTecnica"))
        {
            Object obj = soapObject.getProperty("TipoFichaTecnica");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                tipoFichaTecnica = j.toString();
            }else if (obj!= null && obj instanceof String){
                tipoFichaTecnica = (String) obj;
            }
        }
        if (soapObject.hasProperty("TipoMarcaModelo"))
        {
            Object obj = soapObject.getProperty("TipoMarcaModelo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                tipoMarcaModelo = j.toString();
            }else if (obj!= null && obj instanceof String){
                tipoMarcaModelo = (String) obj;
            }
        }
        if (soapObject.hasProperty("TipoMatricula"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("TipoMatricula");
            tipoMatricula =  new TipoMatricula (j);
            
        }
        if (soapObject.hasProperty("VelocidadMaxima"))
        {
            Object obj = soapObject.getProperty("VelocidadMaxima");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                velocidadMaxima = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                velocidadMaxima = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("VelocidadMaximaSpecified"))
        {
            Object obj = soapObject.getProperty("VelocidadMaximaSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                velocidadMaximaSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                velocidadMaximaSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("fechaModificacion"))
        {
            Object obj = soapObject.getProperty("fechaModificacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaModificacion = j.toString();
            }else if (obj!= null && obj instanceof String){
                fechaModificacion = (String) obj;
            }
        }
        if (soapObject.hasProperty("fechaModificacionSpecified"))
        {
            Object obj = soapObject.getProperty("fechaModificacionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fechaModificacionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                fechaModificacionSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("timestamp"))
        {
            SoapPrimitive j = (SoapPrimitive)soapObject.getProperty("timestamp");
            timestamp = new VectorByte(j);
        }
        if (soapObject.hasProperty("usuarioModificacion"))
        {
            Object obj = soapObject.getProperty("usuarioModificacion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                usuarioModificacion = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                usuarioModificacion = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("usuarioModificacionSpecified"))
        {
            Object obj = soapObject.getProperty("usuarioModificacionSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                usuarioModificacionSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                usuarioModificacionSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("Id"))
        {
            Object obj = soapObject.getProperty("Id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                id = j.toString();
            }else if (obj!= null && obj instanceof String){
                id = (String) obj;
            }
        }
        if (soapObject.hasProperty("Ref"))
        {
            Object obj = soapObject.getProperty("Ref");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ref = j.toString();
            }else if (obj!= null && obj instanceof String){
                ref = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return bastidor;
            case 1:
                return cMA;
            case 2:
                return cMASpecified;
            case 3:
                return cambioManual;
            case 4:
                return cambioManualSpecified;
            case 5:
                return centro;
            case 6:
                return cilindada;
            case 7:
                return cilindadaSpecified;
            case 8:
                return conRemolque;
            case 9:
                return conRemolqueSpecified;
            case 10:
                return conTurbo;
            case 11:
                return conTurboSpecified;
            case 12:
                return contrasenyaHomologacion;
            case 13:
                return cuatroTiempos;
            case 14:
                return cuatroTiemposSpecified;
            case 15:
                return estacionUltimaValidez;
            case 16:
                return extensionBastidor;
            case 17:
                return fK_IdCombustible;
            case 18:
                return fK_IdCombustibleSpecified;
            case 19:
                return fK_IdEstacionUltimaValidez;
            case 20:
                return fK_IdEstacionUltimaValidezSpecified;
            case 21:
                return fK_IdMarcaVehiculo;
            case 22:
                return fK_IdMarcaVehiculoSpecified;
            case 23:
                return fK_IdModeloVehiculo;
            case 24:
                return fK_IdModeloVehiculoSpecified;
            case 25:
                return fK_IdProvinciaPrimeraMatriculacion;
            case 26:
                return fK_IdProvinciaPrimeraMatriculacionSpecified;
            case 27:
                return fK_IdSolicitud;
            case 28:
                return fK_IdSolicitudSpecified;
            case 29:
                return fK_IdTipoMatricula;
            case 30:
                return fK_IdTipoMatriculaSpecified;
            case 31:
                return fK_IdVehiculoClasificacion;
            case 32:
                return fK_IdVehiculoClasificacionSpecified;
            case 33:
                return fechaPrimeraMatriculacion;
            case 34:
                return fechaPrimeraMatriculacionSpecified;
            case 35:
                return fechaUltimaValidez;
            case 36:
                return fechaUltimaValidezSpecified;
            case 37:
                return idSolicitudVehiculoSaliente;
            case 38:
                return idSolicitudVehiculoSalienteSpecified;
            case 39:
                return lugarPrimeraMatriculacion;
            case 40:
                return mOM;
            case 41:
                return mOMSpecified;
            case 42:
                return matricula;
            case 43:
                return notasOcultas;
            case 44:
                return numEjes;
            case 45:
                return numEjesSpecified;
            case 46:
                return observaciones;
            case 47:
                return pMA;
            case 48:
                return pMASpecified;
            case 49:
                return plazas;
            case 50:
                return plazasSpecified;
            case 51:
                return potenciaFiscal;
            case 52:
                return potenciaFiscalSpecified;
            case 53:
                return provincia;
            case 54:
                return publicado;
            case 55:
                return publicadoSpecified;
            case 56:
                return solicitudServicio;
            case 57:
                return tipoFichaTecnica;
            case 58:
                return tipoMarcaModelo;
            case 59:
                return tipoMatricula;
            case 60:
                return velocidadMaxima;
            case 61:
                return velocidadMaximaSpecified;
            case 62:
                return fechaModificacion;
            case 63:
                return fechaModificacionSpecified;
            case 64:
                return timestamp.toString();
            case 65:
                return usuarioModificacion;
            case 66:
                return usuarioModificacionSpecified;
            case 67:
                return id;
            case 68:
                return ref;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 69;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Bastidor";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "CMA";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CMASpecified";
                break;
            case 3:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CambioManual";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CambioManualSpecified";
                break;
            case 5:
                info.type = Centro.class;
                info.name = "Centro";
                break;
            case 6:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Cilindada";
                break;
            case 7:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CilindadaSpecified";
                break;
            case 8:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "ConRemolque";
                break;
            case 9:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "ConRemolqueSpecified";
                break;
            case 10:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "ConTurbo";
                break;
            case 11:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "ConTurboSpecified";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ContrasenyaHomologacion";
                break;
            case 13:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CuatroTiempos";
                break;
            case 14:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CuatroTiemposSpecified";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "EstacionUltimaValidez";
                break;
            case 16:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ExtensionBastidor";
                break;
            case 17:
                info.type = Long.class;
                info.name = "FK_IdCombustible";
                break;
            case 18:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdCombustibleSpecified";
                break;
            case 19:
                info.type = Long.class;
                info.name = "FK_IdEstacionUltimaValidez";
                break;
            case 20:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdEstacionUltimaValidezSpecified";
                break;
            case 21:
                info.type = Long.class;
                info.name = "FK_IdMarcaVehiculo";
                break;
            case 22:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdMarcaVehiculoSpecified";
                break;
            case 23:
                info.type = Long.class;
                info.name = "FK_IdModeloVehiculo";
                break;
            case 24:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdModeloVehiculoSpecified";
                break;
            case 25:
                info.type = Long.class;
                info.name = "FK_IdProvinciaPrimeraMatriculacion";
                break;
            case 26:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdProvinciaPrimeraMatriculacionSpecified";
                break;
            case 27:
                info.type = Long.class;
                info.name = "FK_IdSolicitud";
                break;
            case 28:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdSolicitudSpecified";
                break;
            case 29:
                info.type = Long.class;
                info.name = "FK_IdTipoMatricula";
                break;
            case 30:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdTipoMatriculaSpecified";
                break;
            case 31:
                info.type = Long.class;
                info.name = "FK_IdVehiculoClasificacion";
                break;
            case 32:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FK_IdVehiculoClasificacionSpecified";
                break;
            case 33:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "FechaPrimeraMatriculacion";
                break;
            case 34:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FechaPrimeraMatriculacionSpecified";
                break;
            case 35:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "FechaUltimaValidez";
                break;
            case 36:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "FechaUltimaValidezSpecified";
                break;
            case 37:
                info.type = Long.class;
                info.name = "IdSolicitudVehiculoSaliente";
                break;
            case 38:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "IdSolicitudVehiculoSalienteSpecified";
                break;
            case 39:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "LugarPrimeraMatriculacion";
                break;
            case 40:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "MOM";
                break;
            case 41:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "MOMSpecified";
                break;
            case 42:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Matricula";
                break;
            case 43:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "NotasOcultas";
                break;
            case 44:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "NumEjes";
                break;
            case 45:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "NumEjesSpecified";
                break;
            case 46:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Observaciones";
                break;
            case 47:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "PMA";
                break;
            case 48:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PMASpecified";
                break;
            case 49:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Plazas";
                break;
            case 50:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PlazasSpecified";
                break;
            case 51:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "PotenciaFiscal";
                break;
            case 52:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PotenciaFiscalSpecified";
                break;
            case 53:
                info.type = Provincia.class;
                info.name = "Provincia";
                break;
            case 54:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "Publicado";
                break;
            case 55:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PublicadoSpecified";
                break;
            case 56:
                info.type = SolicitudServicio.class;
                info.name = "SolicitudServicio";
                break;
            case 57:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TipoFichaTecnica";
                break;
            case 58:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TipoMarcaModelo";
                break;
            case 59:
                info.type = TipoMatricula.class;
                info.name = "TipoMatricula";
                break;
            case 60:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "VelocidadMaxima";
                break;
            case 61:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "VelocidadMaximaSpecified";
                break;
            case 62:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "fechaModificacion";
                break;
            case 63:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "fechaModificacionSpecified";
                break;
            case 64:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "timestamp";
                break;
            case 65:
                info.type = Long.class;
                info.name = "usuarioModificacion";
                break;
            case 66:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "usuarioModificacionSpecified";
                break;
            case 67:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Id";
                break;
            case 68:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Ref";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
